/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Switch 3D (https://sketchfab.com/switch3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-nike-killshot-og-sail-gym-red-sneaker-1729c9f875364fe99201722d6ecc5d9f
title: [FREE] Nike Killshot OG Sail Gym Red Sneaker
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tenis.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={20}>
          <mesh geometry={nodes.ZBrush_defualt_group_DefaultMaterial_0.geometry} material={materials.DefaultMaterial} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tenis.gltf')
